###################
### Build image ###
###################

FROM node:16 as build

# Install build dependencies for underlying OS
RUN apt-get update && apt-get install -y g++ build-essential

# Print Node.js & npm versions
RUN node --version
RUN npm --version

# Install the dependencies
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --no-audit

# Build the project
COPY src ./src
COPY public ./public
COPY tools ./tools
COPY .jshintrc ./
COPY eslint.json ./
COPY nodemon.json ./
COPY tsconfig.json ./

RUN npm run build

#####################
### Runtime image ###
#####################

FROM node:16-slim

# Update packages
RUN apt-get update && apt-get install -y git curl procps htop net-tools

# Print Node.js version
RUN node --version

# Copy the required files from the build step
WORKDIR /usr/src/app

COPY --from=build /usr/src/app/src ./src
COPY --from=build /usr/src/app/public ./public
COPY --from=build /usr/src/app/node_modules ./node_modules
COPY --from=build /usr/src/app/dist ./dist
COPY --from=build /usr/src/app/package*.json ./

# Enable logging
RUN mkdir -p /var/log/nodejs && touch /var/log/nodejs/nodejs.log && chown -R node:node /var/log/nodejs

# Add startup scripts
# API
COPY start_api.sh /usr/local/bin/start_api.sh
RUN chmod +x /usr/local/bin/start_api.sh && ln -s /usr/local/bin/start_api.sh /
# ADMIN
COPY start_admin.sh /usr/local/bin/start_admin.sh
RUN chmod +x /usr/local/bin/start_admin.sh && ln -s /usr/local/bin/start_admin.sh /

# Harden Image
COPY ./harden.sh .
RUN chmod +x harden.sh && \
    sh harden.sh && \
    rm -f harden.sh

# Force container to run as a non-root user
USER node
