version: '3'

services:
  ebisusbay-db:
    container_name: ebisusbay-db
    image: mysql:8-oracle
    restart: always
    cap_add:
      - SYS_NICE
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_ROOT_PASSWORD: r00t123
      MYSQL_DATABASE: marketplace
      MYSQL_USER: ebmarketplaceuser
      MYSQL_PASSWORD: verysecret
      MYSQL_ROOT_HOST: "%"
    ports:
      - 3306:3306
    volumes:
      - ./volumes/ebisusbay-db-lib:/var/lib/mysql:rw
      - ./volumes/ebisusbay-db-run:/var/run/mysqld:rw
    user: mysql
    healthcheck:
      test: ["CMD-SHELL", "/usr/bin/mysql --user=root --password=r00t123 --execute \"SHOW DATABASES\";"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 10s

  ebisusbay-api-nginx:
    container_name: ebisusbay-api-nginx
    restart: always
    read_only: true
    build:
      context: .
      dockerfile: ./proxy/Dockerfile_api_local
    environment:
      ## NGINX Amplify Agent
      AMPLIFY_API_KEY: 9eb5c56d5bdd811ea6d0bdb78009cb6f
    healthcheck:
      test: ["CMD-SHELL", "curl -f -s http://localhost:8080/health || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 10s
    volumes:
      - ./volumes/ebisusbay-api-nginx_logs:/var/log/nginx:rw
      - ./volumes/ebisusbay-api-nginx_cache:/var/cache/nginx:rw
      - ./volumes/ebisusbay-api-nginx_pid:/var/run:rw
      - ./volumes/ebisusbay-api-nginx_lib:/var/lib/nginx:rw
      - ./volumes/ebisusbay-api-nginx_amplify_custom_conf:/etc/amplify-agent/custom:rw"
      - ./volumes/ebisusbay-api-nginx_amplify_logs:/var/log/amplify-agent:rw"
    ports:
      - 8080:8080
    depends_on:
      - ebisusbay-api
    links:
      - ebisusbay-api

  ebisusbay-api:
    container_name: ebisusbay-api
    restart: always
    read_only: true
    command: bash -c "start_api.sh"
    build:
      context: .
      dockerfile: Dockerfile_local
    environment:
      ## api setup
      API_HOST: http://localhost:8080
      API_PORT: '3030'
      PORT: '3030'
      ## marketplace data
      AWS_MYSQL_CONN_LIMIT: '1'
      AWS_MYSQL_DATABASE: marketplace
      AWS_MYSQL_HOST: ebisusbay-db
      AWS_MYSQL_PASSWORD: verysecret
      AWS_MYSQL_QUEUE_LIMIT: '0'
      AWS_MYSQL_USER: ebmarketplaceuser
      ## nft metadata
      AWS_S3_BUCKET: prod-ebisusbay-images
      AWS_S3_REGION: us-east-1
      AWS_ACCESS_KEY_ID: AKIA4GBTBBB3ZCO442EM # AWS credentials (required only for local environment)
      AWS_SECRET_ACCESS_KEY: <1Password>
      ## solidity contracts
      ABI_AUCTIONS: ../contract/auctions.json
      ABI_LISTING: ../contract/marketplace.json
      ABI_NFT: ../contract/nft.json
      ABI_NFT_1155: ../contract/ERC1155.json
      ## contract
      CONTRACT_ADDRESS: 0x7a3CdB2364f92369a602CAE81167d0679087e6a3
      AUCTIONS_ADDRESS: 0x08254C5B77615E7B4d2f7df0Dc36e1AEb9025D10
      ## provider
      PROVIDER_TIMEOUT: '300000'
      PROVIDER_URL: https://gateway.nebkas.ro/
      ## ipfs hosts
      IPFS_HOST_EBISUSBAY: https://gateway.ebisusbay.com/ipfs/
      IPFS_HOST_PINATA: https://mygateway.mypinata.cloud/ipfs/
    healthcheck:
      test: ["CMD-SHELL", "curl -f -s http://localhost:3030/health || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 10s
    volumes:
      - ./volumes/ebisusbay-api_logs:/var/log/nodejs:rw
    ports:
      - 3030:3030
    depends_on:
      - ebisusbay-db
    links:
      - ebisusbay-db

  ebisusbay-admin-nginx:
    container_name: ebisusbay-admin-nginx
    restart: always
    read_only: true
    build:
      context: .
      dockerfile: ./proxy/Dockerfile_admin_local
    healthcheck:
      test: ["CMD-SHELL", "curl -f -s http://localhost:8888/health || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 10s
    volumes:
      - ./volumes/ebisusbay-admin-nginx_logs:/var/log/nginx:rw
      - ./volumes/ebisusbay-admin-nginx_cache:/var/cache/nginx:rw
      - ./volumes/ebisusbay-admin-nginx_pid:/var/run:rw
    ports:
      - 8888:8888
    depends_on:
      - ebisusbay-admin
    links:
      - ebisusbay-admin

  ebisusbay-admin:
    container_name: ebisusbay-admin
    restart: always
    read_only: true
    command: bash -c "start_admin.sh"
    build:
      context: .
      dockerfile: Dockerfile_local
    environment:
      ## admin setup
      ADMIN_HOST: http://localhost:8888
      ADMIN_JOBS: 'ON'
      ADMIN_PORT: '3333'
      PORT: '3333'
      API_HOST: http://localhost:8888
      ## marketplace data
      AWS_MYSQL_CONN_LIMIT: '1'
      AWS_MYSQL_DATABASE: marketplace
      AWS_MYSQL_HOST: ebisusbay-db
      AWS_MYSQL_PASSWORD: verysecret
      AWS_MYSQL_QUEUE_LIMIT: '0'
      AWS_MYSQL_USER: ebmarketplaceuser
      ## nft metadata
      AWS_S3_BUCKET: prod-ebisusbay-images
      AWS_S3_REGION: us-east-1
      AWS_ACCESS_KEY_ID: AKIA4GBTBBB3ZCO442EM # AWS credentials (required only for local environment)
      AWS_SECRET_ACCESS_KEY: <1Password>
      ## solidity contracts
      ABI_AUCTIONS: ../contract/auctions.json
      ABI_LISTING: ../contract/marketplace.json
      ABI_NFT: ../contract/nft.json
      ABI_NFT_1155: ../contract/ERC1155.json
      ## contract
      CONTRACT_ADDRESS: 0x7a3CdB2364f92369a602CAE81167d0679087e6a3
      AUCTIONS_ADDRESS: 0x08254C5B77615E7B4d2f7df0Dc36e1AEb9025D10
      ## provider
      PROVIDER_TIMEOUT: '300000'
      PROVIDER_URL: https://gateway.nebkas.ro/
      ## ipfs hosts
      IPFS_HOST_EBISUSBAY: https://gateway.ebisusbay.com/ipfs/
      IPFS_HOST_PINATA: https://mygateway.mypinata.cloud/ipfs/
    healthcheck:
      test: ["CMD-SHELL", "curl -f -s http://localhost:3333/health || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 20s
    volumes:
      - ./volumes/ebisusbay-admin_logs:/var/log/nodejs:rw
    ports:
      - 3333:3333
    depends_on:
      - ebisusbay-db
    links:
      - ebisusbay-db
