FROM nginx:latest

COPY proxy/nginx.conf /etc/nginx/nginx.conf
#COPY proxy/conf.d/default.conf /etc/nginx/conf.d/default.conf
COPY proxy/conf.d/admin.conf /etc/nginx/conf.d/admin.conf
COPY proxy/conf.d/security_headers.conf /etc/nginx/conf.d/security_headers.conf

# Install tools
RUN apt-get update && apt-get install -y curl procps htop

COPY proxy/entrypoint_admin_local.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
